apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-counter-deployment
  labels:
    app: k8s-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-counter
  template:
    metadata:
      labels:
        app: k8s-counter
    spec:
      containers:
      - name: k8s-counter
        image: wallnerryan/moby-counter:v1.21
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: USE_POSTGRES_HOST
          value: "a3eaa662a68bd4bd6a456717efee6208-1105767480.us-east-1.elb.amazonaws.com"
        - name: USE_POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "pds"
        - name: POSTGRES_PASSWORD
          value: "2yCUd04SgZs0ZCho9hVapy800dbVWl7TyI4HDviq"
        - name: POSTGRES_DB
          value: "pds"
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-counter-service
spec:
  type: LoadBalancer
  selector:
    app: k8s-counter
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30123
    name: k8s-counter-web

