apiVersion: portworx.io/v1beta2
kind: VolumePlacementStrategy
metadata:
  name: mongo-sts-volume-affinity
spec:
  volumeAffinity:
    - matchExpressions:
      - key: px/statefulset-pod
        operator: In
        values:
        - "${pvc.statefulset-pod}"
      - key: app
        operator: In
        values:
        - "mongo-sts"
